### ISSUE TITLE
DevContainerでシナリオテスト実行するときすんなりいかんかった

### ISSUE THREAD

**Issue by nabekuro0104** [SSL-Roots/consai_ros2#193]
## ローカル開発時の手順メモ

- `.devcontainer/devcontainer.json` の `"forwardPorts": [3000, 8081, 9090],` を削除すると便利
    - 毎回VSCode側でStop Forwarding Portをしなくても良い

### シナリオテストを実行する

- `.devcontainer/docker-compose.yml`のgrsim部分を以下に書き換える
    ```
    grsim:
        image: ghcr.io/ssl-roots/docker_images/grsim:main
        container_name: grsim
        command: |
        ./grSim --headless -platform offscreen
        tty: true
        stdin_open: true
        restart: "no"
    ```
- DevContainer起動後、 `ssl-game-controller` を停止する
    - シナリオテストで送信されるコマンドと競合するため
    - ホスト側のターミナルでdockerコマンドで停止してもよいし、VSCodeの拡張機能メニュー「リモートエクスプローラー」から`consai_ros2_devcontainer-ssl-game-controller-1` を右クリックで停止が楽
- シナリオテスト用に色々準備
    ```
    # Install Google Protobuf Compiler
    sudo apt install protobuf-compiler

    # Install pip
    sudo apt install pip

    # Install rcst
    pip install -v git+https://github.com/SSL-Roots/robocup_scenario_test
    ```
- 下記のようなコマンドでシナリオ実行
    ```
    pytest-3 tests/test_scenario_force_start.py --vision_port=10020 --sim_addr='grsim'
    ```
    - `--sim_addr='grsim'` が必要
